### ISSUE TITLE
Adding Go support but files still have `.cs` extension

### ISSUE THREAD

**Issue by grokify** [tylerlong/rc-codegen#6]
I've added some initial support for Go but the auto-generated files still have the `.cs` extension when I use `.go` in the `go/index.ts` file:

* Repo: https://github.com/grokify/rc-codegen/tree/955569ff401f3268ae43cb834a986dc781aa32e7
* Definitions extension: https://github.com/grokify/rc-codegen/blob/955569ff401f3268ae43cb834a986dc781aa32e7/go/index.ts#L80

Command:

```
$ yarn run go
yarn run v0.18.1
$ node index.js -l go -o ~/src/go/ringcentral-sdk-go -t ~/src/ts/rc-codegen/go/views 
./go/index
✨  Done in 0.44s.
```

The auto-generated definition files do use the templates in `go/views` but end up with the `.cs` extension.

What am I missing?

**Comment by zengfenfei** [comment]
I think you should add `go/index.ts` to the `files` section of `tsconfig.json`.  Just try it, I can generate files with `.go` extension.

**Comment by grokify** [comment]
@zengfenfei That solved the issue. Thanks!

Strange that it would still run and create files with `.cs` extension without that file.
